
version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "hello-world-app/yarn.lock" }}
      - run:
          name: install
          command: yarn
          working_directory: hello-world-app
      - save_cache:
          key: dependency-cache-{{ checksum "hello-world-app/yarn.lock" }}
          paths:
            - hello-world-app/node_modules
      - run:
          name: build
          command: yarn build
          working_directory: hello-world-app
  
  hello:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "hello world"

workflows:
  version: 2
  build:
    jobs:
      - hello
      - build
        requires:
          - hello
