
version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "hello-world-app/package.json" }}
      - run:
          name: install
          command: yarn
          working_directory: hello-world-app
      - save_cache:
          key: dependency-cache-{{ checksum "hello-world-app/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
          working_directory: hello-world-app

      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      # - store_test_results:
      #     path: test-results.xml